version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: warranty_db
    restart: always
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - warranty_network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d

  backend:
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    container_name: warranty_backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "node -e 'require(\"http\").get(\"http://localhost:3000/api/test\", res => process.exit(res.statusCode === 200 ? 0 : 1))'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    networks:
      - warranty_network
    volumes:
      - ./src/backend/uploads:/app/uploads
    environment:
      NODE_ENV: production

  adminer:
    image: adminer:latest
    container_name: warranty_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - warranty_network
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DEFAULT_DATABASE: ${DB_DATABASE}

volumes:
  mysql_data: {}

networks:
  warranty_network:
    driver: bridge
