version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: warranty_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - warranty_network

  backend:
    build:
      context: ./src/backend  # Path to your backend Dockerfile
    container_name: warranty_backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql  # Use container name for database connection
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    networks:
      - warranty_network

  nginx:
    build:
      context: ./src/frontend/nginx  # Path to the directory containing nginx.conf
    container_name: warranty_nginx
    restart: always
    ports:
      - '80:80'
    depends_on:
      - backend  # Nginx depends on the backend
    networks:
      - warranty_network

volumes:
  mysql_data:

networks:
  warranty_network:
    driver: bridge