name: Deploy warranty-wallet to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy warranty-wallet to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (za frontend build)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: ./src/frontend
        run: npm install

      - name: Build frontend (vite build)
        working-directory: ./src/frontend
        run: npm run build

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.CICD_DEPLOY_KEY }}

      - name: Add VPS to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 206.189.59.75 >> ~/.ssh/known_hosts

      - name: Sync frontend build to VPS
        run: |
          rsync -avz --delete ./src/frontend/dist/ root@206.189.59.75:/home/root/projects/warranty-wallet/src/frontend/dist/

      - name: Deploy backend and restart Docker services on VPS
        env:
          PROD_ENV_VARS: ${{ secrets.PROD_ENV_FILE }}
        run: |
          ssh root@206.189.59.75 << EOF
            cd /home/root/projects/warranty-wallet

            # Update .env.production sa tajnama iz GitHub Secrets (koristeći printf da ne preseče ključ)
            printf "%s" "${PROD_ENV_VARS}" > .env.production

            # Osveži backend kod na VPS-u
            git fetch --all
            git reset --hard origin/main

            # Povuci nove docker slike (mysql, adminer)
            docker compose -f docker-compose.yml pull

            # Restartuj kontejnere sa rebuild-om backend servisa
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d --build
          EOF
